<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            // Andhra Pradesh (AP) - state_id 1
            ['id' => 1, 'name' => 'Adilabad', 'state_id' => 1],
            ['id' => 2, 'name' => 'Anantapur', 'state_id' => 1],
            ['id' => 3, 'name' => 'Chittoor', 'state_id' => 1],
            ['id' => 4, 'name' => 'Kakinada', 'state_id' => 1],
            ['id' => 5, 'name' => 'Guntur', 'state_id' => 1],
            ['id' => 6, 'name' => 'Hyderabad', 'state_id' => 1],
            ['id' => 7, 'name' => 'Karimnagar', 'state_id' => 1],
            ['id' => 8, 'name' => 'Khammam', 'state_id' => 1],
            ['id' => 9, 'name' => 'Krishna', 'state_id' => 1],
            ['id' => 10, 'name' => 'Kurnool', 'state_id' => 1],
            ['id' => 11, 'name' => 'Mahbubnagar', 'state_id' => 1],
            ['id' => 12, 'name' => 'Medak', 'state_id' => 1],
            ['id' => 13, 'name' => 'Nalgonda', 'state_id' => 1],
            ['id' => 14, 'name' => 'Nizamabad', 'state_id' => 1],
            ['id' => 15, 'name' => 'Ongole', 'state_id' => 1],
            ['id' => 16, 'name' => 'Srikakulam', 'state_id' => 1],
            ['id' => 17, 'name' => 'Nellore', 'state_id' => 1],
            ['id' => 18, 'name' => 'Visakhapatnam', 'state_id' => 1],
            ['id' => 19, 'name' => 'Vizianagaram', 'state_id' => 1],
            ['id' => 20, 'name' => 'Warangal', 'state_id' => 1],
            ['id' => 21, 'name' => 'Eluru', 'state_id' => 1],
            ['id' => 22, 'name' => 'Kadapa', 'state_id' => 1],

            // Arunachal Pradesh (AR) - state_id 2
            ['id' => 23, 'name' => 'Anjaw', 'state_id' => 2],
            ['id' => 24, 'name' => 'Changlang', 'state_id' => 2],
            ['id' => 25, 'name' => 'East Siang', 'state_id' => 2],
            ['id' => 26, 'name' => 'Kurung Kumey', 'state_id' => 2],
            ['id' => 27, 'name' => 'Lohit', 'state_id' => 2],
            ['id' => 28, 'name' => 'Lower Dibang Valley', 'state_id' => 2],
            ['id' => 29, 'name' => 'Lower Subansiri', 'state_id' => 2],
            ['id' => 30, 'name' => 'Papum Pare', 'state_id' => 2],
            ['id' => 31, 'name' => 'Tawang', 'state_id' => 2],
            ['id' => 32, 'name' => 'Tirap', 'state_id' => 2],
            ['id' => 33, 'name' => 'Dibang Valley', 'state_id' => 2],
            ['id' => 34, 'name' => 'Upper Siang', 'state_id' => 2],
            ['id' => 35, 'name' => 'Upper Subansiri', 'state_id' => 2],
            ['id' => 36, 'name' => 'West Kameng', 'state_id' => 2],
            ['id' => 37, 'name' => 'West Siang', 'state_id' => 2],

            // Assam (AS) - state_id 3
            ['id' => 38, 'name' => 'Baksa', 'state_id' => 3],
            ['id' => 39, 'name' => 'Barpeta', 'state_id' => 3],
            ['id' => 40, 'name' => 'Bongaigaon', 'state_id' => 3],
            ['id' => 41, 'name' => 'Cachar', 'state_id' => 3],
            ['id' => 42, 'name' => 'Chirang', 'state_id' => 3],
            ['id' => 43, 'name' => 'Darrang', 'state_id' => 3],
            ['id' => 44, 'name' => 'Dhemaji', 'state_id' => 3],
            ['id' => 45, 'name' => 'Dima Hasao', 'state_id' => 3],
            ['id' => 46, 'name' => 'Dhubri', 'state_id' => 3],
            ['id' => 47, 'name' => 'Dibrugarh', 'state_id' => 3],
            ['id' => 48, 'name' => 'Goalpara', 'state_id' => 3],
            ['id' => 49, 'name' => 'Golaghat', 'state_id' => 3],
            ['id' => 50, 'name' => 'Hailakandi', 'state_id' => 3],
            ['id' => 51, 'name' => 'Jorhat', 'state_id' => 3],
            ['id' => 52, 'name' => 'Kamrup', 'state_id' => 3],
            ['id' => 53, 'name' => 'Kamrup Metropolitan', 'state_id' => 3],
            ['id' => 54, 'name' => 'Karbi Anglong', 'state_id' => 3],
            ['id' => 55, 'name' => 'Karimganj', 'state_id' => 3],
            ['id' => 56, 'name' => 'Kokrajhar', 'state_id' => 3],
            ['id' => 57, 'name' => 'Lakhimpur', 'state_id' => 3],
            ['id' => 58, 'name' => 'Marigaon', 'state_id' => 3],
            ['id' => 59, 'name' => 'Nagaon', 'state_id' => 3],
            ['id' => 60, 'name' => 'Nalbari', 'state_id' => 3],
            ['id' => 61, 'name' => 'Sibsagar', 'state_id' => 3],
            ['id' => 62, 'name' => 'Sonitpur', 'state_id' => 3],
            ['id' => 63, 'name' => 'Tinsukia', 'state_id' => 3],
            ['id' => 64, 'name' => 'Udalguri', 'state_id' => 3],

            // Bihar (BR) - state_id 4
            ['id' => 65, 'name' => 'Araria', 'state_id' => 4],
            ['id' => 66, 'name' => 'Arwal', 'state_id' => 4],
            ['id' => 67, 'name' => 'Aurangabad', 'state_id' => 4],
            ['id' => 68, 'name' => 'Banka', 'state_id' => 4],
            ['id' => 69, 'name' => 'Begusarai', 'state_id' => 4],
            ['id' => 70, 'name' => 'Bhagalpur', 'state_id' => 4],
            ['id' => 71, 'name' => 'Bhojpur', 'state_id' => 4],
            ['id' => 72, 'name' => 'Buxar', 'state_id' => 4],
            ['id' => 73, 'name' => 'Darbhanga', 'state_id' => 4],
            ['id' => 74, 'name' => 'East Champaran', 'state_id' => 4],
            ['id' => 75, 'name' => 'Gaya', 'state_id' => 4],
            ['id' => 76, 'name' => 'Gopalganj', 'state_id' => 4],
            ['id' => 77, 'name' => 'Jamui', 'state_id' => 4],
            ['id' => 78, 'name' => 'Jehanabad', 'state_id' => 4],
            ['id' => 79, 'name' => 'Kaimur', 'state_id' => 4],
            ['id' => 80, 'name' => 'Katihar', 'state_id' => 4],
            ['id' => 81, 'name' => 'Khagaria', 'state_id' => 4],
            ['id' => 82, 'name' => 'Kishanganj', 'state_id' => 4],
            ['id' => 83, 'name' => 'Lakhisarai', 'state_id' => 4],
            ['id' => 84, 'name' => 'Madhepura', 'state_id' => 4],
            ['id' => 85, 'name' => 'Madhubani', 'state_id' => 4],
            ['id' => 86, 'name' => 'Munger', 'state_id' => 4],
            ['id' => 87, 'name' => 'Muzaffarpur', 'state_id' => 4],
            ['id' => 88, 'name' => 'Nalanda', 'state_id' => 4],
            ['id' => 89, 'name' => 'Nawada', 'state_id' => 4],
            ['id' => 90, 'name' => 'Patna', 'state_id' => 4],
            ['id' => 91, 'name' => 'Purnia', 'state_id' => 4],
            ['id' => 92, 'name' => 'Rohtas', 'state_id' => 4],
            ['id' => 93, 'name' => 'Saharsa', 'state_id' => 4],
            ['id' => 94, 'name' => 'Samastipur', 'state_id' => 4],
            ['id' => 95, 'name' => 'Saran', 'state_id' => 4],
            ['id' => 96, 'name' => 'Sheikhpura', 'state_id' => 4],
            ['id' => 97, 'name' => 'Sheohar', 'state_id' => 4],
            ['id' => 98, 'name' => 'Sitamarhi', 'state_id' => 4],
            ['id' => 99, 'name' => 'Siwan', 'state_id' => 4],
            ['id' => 100, 'name' => 'Supaul', 'state_id' => 4],
            ['id' => 101, 'name' => 'Vaishali', 'state_id' => 4],
            ['id' => 102, 'name' => 'West Champaran', 'state_id' => 4],
            ['id' => 103, 'name' => 'Chandigarh', 'state_id' => 4],

              // Chhattisgarh (CG) - state_id 5
              ['id' => 104, 'name' => 'Bastar', 'state_id' => 5],
              ['id' => 105, 'name' => 'Bijapur', 'state_id' => 5],
              ['id' => 106, 'name' => 'Bilaspur', 'state_id' => 5],
              ['id' => 107, 'name' => 'Dantewada', 'state_id' => 5],
              ['id' => 108, 'name' => 'Dhamtari', 'state_id' => 5],
              ['id' => 109, 'name' => 'Durg', 'state_id' => 5],
              ['id' => 110, 'name' => 'Jashpur', 'state_id' => 5],
              ['id' => 111, 'name' => 'Janjgir-Champa', 'state_id' => 5],
              ['id' => 112, 'name' => 'Korba', 'state_id' => 5],
              ['id' => 113, 'name' => 'Koriya', 'state_id' => 5],
              ['id' => 114, 'name' => 'Kanker', 'state_id' => 5],
              ['id' => 115, 'name' => 'Kabirdham (Kawardha)', 'state_id' => 5],
              ['id' => 116, 'name' => 'Mahasamund', 'state_id' => 5],
              ['id' => 117, 'name' => 'Narayanpur', 'state_id' => 5],
              ['id' => 118, 'name' => 'Raigarh', 'state_id' => 5],
              ['id' => 119, 'name' => 'Rajnandgaon', 'state_id' => 5],
              ['id' => 120, 'name' => 'Raipur', 'state_id' => 5],
              ['id' => 121, 'name' => 'Surguja', 'state_id' => 5],
              
            // Dadra and Nagar Haveli (DN) - state_id 6
            ['id' => 122, 'name' => 'Dadra and Nagar Haveli', 'state_id' => 6],

            // Daman and Diu (DD) - state_id 7
            ['id' => 123, 'name' => 'Daman', 'state_id' => 7],
            ['id' => 124, 'name' => 'Diu', 'state_id' => 7],

            // Delhi (DL) - state_id 8
            ['id' => 125, 'name' => 'Central Delhi', 'state_id' => 8],
            ['id' => 126, 'name' => 'East Delhi', 'state_id' => 8],
            ['id' => 127, 'name' => 'New Delhi', 'state_id' => 8],
            ['id' => 128, 'name' => 'North Delhi', 'state_id' => 8],
            ['id' => 129, 'name' => 'North East Delhi', 'state_id' => 8],
            ['id' => 130, 'name' => 'North West Delhi', 'state_id' => 8],
            ['id' => 131, 'name' => 'South Delhi', 'state_id' => 8],
            ['id' => 132, 'name' => 'South West Delhi', 'state_id' => 8],
            ['id' => 133, 'name' => 'West Delhi', 'state_id' => 8],

            // Goa (GA) - state_id 9
            ['id' => 134, 'name' => 'North Goa', 'state_id' => 9],
            ['id' => 135, 'name' => 'South Goa', 'state_id' => 9],

            // Gujarat (GJ) - state_id 10
            ['id' => 136, 'name' => 'Ahmedabad', 'state_id' => 10],
            ['id' => 137, 'name' => 'Amreli district', 'state_id' => 10],
            ['id' => 138, 'name' => 'Anand', 'state_id' => 10],
            ['id' => 139, 'name' => 'Banaskantha', 'state_id' => 10],
            ['id' => 140, 'name' => 'Bharuch', 'state_id' => 10],
            ['id' => 141, 'name' => 'Bhavnagar', 'state_id' => 10],
            ['id' => 142, 'name' => 'Dahod', 'state_id' => 10],
            ['id' => 143, 'name' => 'The Dangs', 'state_id' => 10],
            ['id' => 144, 'name' => 'Gandhinagar', 'state_id' => 10],
            ['id' => 145, 'name' => 'Jamnagar', 'state_id' => 10],
            ['id' => 146, 'name' => 'Junagadh', 'state_id' => 10],
            ['id' => 147, 'name' => 'Kutch', 'state_id' => 10],
            ['id' => 148, 'name' => 'Kheda', 'state_id' => 10],
            ['id' => 149, 'name' => 'Mehsana', 'state_id' => 10],
            ['id' => 150, 'name' => 'Narmada', 'state_id' => 10],
            ['id' => 151, 'name' => 'Navsari', 'state_id' => 10],
            ['id' => 152, 'name' => 'Patan', 'state_id' => 10],
            ['id' => 153, 'name' => 'Panchmahal', 'state_id' => 10],
            ['id' => 154, 'name' => 'Porbandar', 'state_id' => 10],
            ['id' => 155, 'name' => 'Rajkot', 'state_id' => 10],
            ['id' => 156, 'name' => 'Sabarkantha', 'state_id' => 10],
            ['id' => 157, 'name' => 'Surendranagar', 'state_id' => 10],
            ['id' => 158, 'name' => 'Surat', 'state_id' => 10],
            ['id' => 159, 'name' => 'Vyara', 'state_id' => 10],
            ['id' => 160, 'name' => 'Vadodara', 'state_id' => 10],
            ['id' => 161, 'name' => 'Valsad', 'state_id' => 10],
  
            // Haryana (HR) - state_id 11
            ['id' => 162, 'name' => 'Ambala', 'state_id' => 11],
            ['id' => 163, 'name' => 'Bhiwani', 'state_id' => 11],
            ['id' => 164, 'name' => 'Faridabad', 'state_id' => 11],
            ['id' => 165, 'name' => 'Fatehabad', 'state_id' => 11],
            ['id' => 166, 'name' => 'Gurgaon', 'state_id' => 11],
            ['id' => 167, 'name' => 'Hissar', 'state_id' => 11],
            ['id' => 168, 'name' => 'Jhajjar', 'state_id' => 11],
            ['id' => 169, 'name' => 'Jind', 'state_id' => 11],
            ['id' => 170, 'name' => 'Karnal', 'state_id' => 11],
            ['id' => 171, 'name' => 'Kaithal', 'state_id' => 11],
            ['id' => 172, 'name' => 'Kurukshetra', 'state_id' => 11],
            ['id' => 173, 'name' => 'Mahendragarh', 'state_id' => 11],
            ['id' => 174, 'name' => 'Mewat', 'state_id' => 11],
            ['id' => 175, 'name' => 'Palwal', 'state_id' => 11],
            ['id' => 176, 'name' => 'Panchkula', 'state_id' => 11],
            ['id' => 177, 'name' => 'Panipat', 'state_id' => 11],
            ['id' => 178, 'name' => 'Rewari', 'state_id' => 11],
            ['id' => 179, 'name' => 'Rohtak', 'state_id' => 11],
            ['id' => 180, 'name' => 'Sirsa', 'state_id' => 11],
            ['id' => 181, 'name' => 'Sonipat', 'state_id' => 11],
            ['id' => 182, 'name' => 'Yamuna Nagar', 'state_id' => 11],

            // Himachal Pradesh (HP) - state_id 12
            ['id' => 183, 'name' => 'Bilaspur', 'state_id' => 12],
            ['id' => 184, 'name' => 'Chamba', 'state_id' => 12],
            ['id' => 185, 'name' => 'Hamirpur', 'state_id' => 12],
            ['id' => 186, 'name' => 'Kangra', 'state_id' => 12],
            ['id' => 187, 'name' => 'Kinnaur', 'state_id' => 12],
            ['id' => 188, 'name' => 'Kullu', 'state_id' => 12],
            ['id' => 189, 'name' => 'Lahaul and Spiti', 'state_id' => 12],
            ['id' => 190, 'name' => 'Mandi', 'state_id' => 12],
            ['id' => 191, 'name' => 'Shimla', 'state_id' => 12],
            ['id' => 192, 'name' => 'Sirmaur', 'state_id' => 12],
            ['id' => 193, 'name' => 'Solan', 'state_id' => 12],
            ['id' => 194, 'name' => 'Una', 'state_id' => 12],

            // Jammu and Kashmir (JK) - state_id 13
            ['id' => 195, 'name' => 'Anantnag', 'state_id' => 13],
            ['id' => 196, 'name' => 'Badgam', 'state_id' => 13],
            ['id' => 197, 'name' => 'Bandipora', 'state_id' => 13],
            ['id' => 198, 'name' => 'Baramulla', 'state_id' => 13],
            ['id' => 199, 'name' => 'Doda', 'state_id' => 13],
            ['id' => 200, 'name' => 'Ganderbal', 'state_id' => 13],
            ['id' => 201, 'name' => 'Jammu', 'state_id' => 13],
            ['id' => 202, 'name' => 'Kargil', 'state_id' => 13],
            ['id' => 203, 'name' => 'Kathua', 'state_id' => 13],
            ['id' => 204, 'name' => 'Kishtwar', 'state_id' => 13],
            ['id' => 205, 'name' => 'Kupwara', 'state_id' => 13],
            ['id' => 206, 'name' => 'Kulgam', 'state_id' => 13],
            ['id' => 207, 'name' => 'Leh', 'state_id' => 13],
            ['id' => 208, 'name' => 'Poonch', 'state_id' => 13],
            ['id' => 209, 'name' => 'Pulwama', 'state_id' => 13],
            ['id' => 210, 'name' => 'Rajauri', 'state_id' => 13],
            ['id' => 211, 'name' => 'Ramban', 'state_id' => 13],
            ['id' => 212, 'name' => 'Reasi', 'state_id' => 13],
            ['id' => 213, 'name' => 'Samba', 'state_id' => 13],
            ['id' => 214, 'name' => 'Shopian', 'state_id' => 13],
            ['id' => 215, 'name' => 'Srinagar', 'state_id' => 13],
            ['id' => 216, 'name' => 'Udhampur', 'state_id' => 13],

            // Jharkhand (JH) - state_id 14
            ['id' => 217, 'name' => 'Bokaro', 'state_id' => 14],
            ['id' => 218, 'name' => 'Chatra', 'state_id' => 14],
            ['id' => 219, 'name' => 'Deoghar', 'state_id' => 14],
            ['id' => 220, 'name' => 'Dhanbad', 'state_id' => 14],
            ['id' => 221, 'name' => 'Dumka', 'state_id' => 14],
            ['id' => 222, 'name' => 'East Singhbhum', 'state_id' => 14],
            ['id' => 223, 'name' => 'Garhwa', 'state_id' => 14],
            ['id' => 224, 'name' => 'Giridih', 'state_id' => 14],
            ['id' => 225, 'name' => 'Godda', 'state_id' => 14],
            ['id' => 226, 'name' => 'Gumla', 'state_id' => 14],
            ['id' => 227, 'name' => 'Hazaribag', 'state_id' => 14],
            ['id' => 228, 'name' => 'Jamtara', 'state_id' => 14],
            ['id' => 229, 'name' => 'Khunti', 'state_id' => 14],
            ['id' => 230, 'name' => 'Koderma', 'state_id' => 14],
            ['id' => 231, 'name' => 'Latehar', 'state_id' => 14],
            ['id' => 232, 'name' => 'Lohardaga', 'state_id' => 14],
            ['id' => 233, 'name' => 'Pakur', 'state_id' => 14],
            ['id' => 234, 'name' => 'Palamu', 'state_id' => 14],
            ['id' => 235, 'name' => 'Ramgarh', 'state_id' => 14],
            ['id' => 236, 'name' => 'Ranchi', 'state_id' => 14],
            ['id' => 237, 'name' => 'Sahibganj', 'state_id' => 14],
            ['id' => 238, 'name' => 'Seraikela Kharsawan', 'state_id' => 14],
            ['id' => 239, 'name' => 'Simdega', 'state_id' => 14],
            ['id' => 240, 'name' => 'West Singhbhum', 'state_id' => 14],

            // Karnataka (KA) - state_id 15
            ['id' => 241, 'name' => 'Bagalkot', 'state_id' => 15],
            ['id' => 242, 'name' => 'Bangalore Rural', 'state_id' => 15],
            ['id' => 243, 'name' => 'Bangalore Urban', 'state_id' => 15],
            ['id' => 244, 'name' => 'Belgaum', 'state_id' => 15],
            ['id' => 245, 'name' => 'Bellary', 'state_id' => 15],
            ['id' => 246, 'name' => 'Bidar', 'state_id' => 15],
            ['id' => 247, 'name' => 'Bijapur', 'state_id' => 15],
            ['id' => 248, 'name' => 'Chamarajnagar', 'state_id' => 15],
            ['id' => 249, 'name' => 'Chikkamagaluru', 'state_id' => 15],
            ['id' => 250, 'name' => 'Chikkaballapur', 'state_id' => 15],
            ['id' => 251, 'name' => 'Chitradurga', 'state_id' => 15],
            ['id' => 252, 'name' => 'Davanagere', 'state_id' => 15],
            ['id' => 253, 'name' => 'Dharwad', 'state_id' => 15],
            ['id' => 254, 'name' => 'Dakshina Kannada', 'state_id' => 15],
            ['id' => 255, 'name' => 'Gadag', 'state_id' => 15],
            ['id' => 256, 'name' => 'Gulbarga', 'state_id' => 15],
            ['id' => 257, 'name' => 'Hassan', 'state_id' => 15],
            ['id' => 258, 'name' => 'Haveri district', 'state_id' => 15],
            ['id' => 259, 'name' => 'Kodagu', 'state_id' => 15],
            ['id' => 260, 'name' => 'Kolar', 'state_id' => 15],
            ['id' => 261, 'name' => 'Koppal', 'state_id' => 15],
            ['id' => 262, 'name' => 'Mandya', 'state_id' => 15],
            ['id' => 263, 'name' => 'Mysore', 'state_id' => 15],
            ['id' => 264, 'name' => 'Raichur', 'state_id' => 15],
            ['id' => 265, 'name' => 'Shimoga', 'state_id' => 15],
            ['id' => 266, 'name' => 'Tumkur', 'state_id' => 15],
            ['id' => 267, 'name' => 'Udupi', 'state_id' => 15],
            ['id' => 268, 'name' => 'Uttara Kannada', 'state_id' => 15],
            ['id' => 269, 'name' => 'Ramanagara', 'state_id' => 15],
            ['id' => 270, 'name' => 'Yadgir', 'state_id' => 15],

            // Kerala (KL) - state_id 16
            ['id' => 271, 'name' => 'Alappuzha', 'state_id' => 16],
            ['id' => 272, 'name' => 'Ernakulam', 'state_id' => 16],
            ['id' => 273, 'name' => 'Idukki', 'state_id' => 16],
            ['id' => 274, 'name' => 'Kannur', 'state_id' => 16],
            ['id' => 275, 'name' => 'Kasaragod', 'state_id' => 16],
            ['id' => 276, 'name' => 'Kollam', 'state_id' => 16],
            ['id' => 277, 'name' => 'Kottayam', 'state_id' => 16],
            ['id' => 278, 'name' => 'Kozhikode', 'state_id' => 16],
            ['id' => 279, 'name' => 'Malappuram', 'state_id' => 16],
            ['id' => 280, 'name' => 'Palakkad', 'state_id' => 16],
            ['id' => 281, 'name' => 'Pathanamthitta', 'state_id' => 16],
            ['id' => 282, 'name' => 'Thiruvananthapuram', 'state_id' => 16],
            ['id' => 283, 'name' => 'Thrissur', 'state_id' => 16],
            ['id' => 284, 'name' => 'Wayanad', 'state_id' => 16],

            // Ladakh (LA) - state_id 17
            ['id' => 285, 'name' => 'Leh', 'state_id' => 17],
            ['id' => 286, 'name' => 'Kargil', 'state_id' => 17],

            // Lakshadweep (LD) - state_id 18
            ['id' => 287, 'name' => 'Lakshadweep', 'state_id' => 18],

            // Madhya Pradesh (MP) - state_id 19
            ['id' => 288, 'name' => 'Agar Malwa', 'state_id' => 19],
            ['id' => 289, 'name' => 'Alirajpur', 'state_id' => 19],
            ['id' => 290, 'name' => 'Anuppur', 'state_id' => 19],
            ['id' => 291, 'name' => 'Ashok Nagar', 'state_id' => 19],
            ['id' => 292, 'name' => 'Balaghat', 'state_id' => 19],
            ['id' => 293, 'name' => 'Barwani', 'state_id' => 19],
            ['id' => 294, 'name' => 'Betul', 'state_id' => 19],
            ['id' => 295, 'name' => 'Bhind', 'state_id' => 19],
            ['id' => 296, 'name' => 'Bhopal', 'state_id' => 19],
            ['id' => 297, 'name' => 'Burhanpur', 'state_id' => 19],
            ['id' => 298, 'name' => 'Chhatarpur', 'state_id' => 19],
            ['id' => 299, 'name' => 'Chhindwara', 'state_id' => 19],
            ['id' => 300, 'name' => 'Damoh', 'state_id' => 19],
            ['id' => 301, 'name' => 'Datia', 'state_id' => 19],
            ['id' => 302, 'name' => 'Dewas', 'state_id' => 19],
            ['id' => 303, 'name' => 'Dhar', 'state_id' => 19],
            ['id' => 304, 'name' => 'Guna', 'state_id' => 19],
            ['id' => 305, 'name' => 'Gwalior', 'state_id' => 19],
            ['id' => 306, 'name' => 'Harda', 'state_id' => 19],
            ['id' => 307, 'name' => 'Hoshangabad', 'state_id' => 19],
            ['id' => 308, 'name' => 'Indore', 'state_id' => 19],
            ['id' => 309, 'name' => 'Jabalpur', 'state_id' => 19],
            ['id' => 310, 'name' => 'Jhabua', 'state_id' => 19],
            ['id' => 311, 'name' => 'Katni', 'state_id' => 19],
            ['id' => 312, 'name' => 'Khandwa', 'state_id' => 19],
            ['id' => 313, 'name' => 'Khargone', 'state_id' => 19],
            ['id' => 314, 'name' => 'Mandla', 'state_id' => 19],
            ['id' => 315, 'name' => 'Mandsaur', 'state_id' => 19],
            ['id' => 316, 'name' => 'Morena', 'state_id' => 19],
            ['id' => 317, 'name' => 'Narmada', 'state_id' => 19],
            ['id' => 318, 'name' => 'Neemuch', 'state_id' => 19],
            ['id' => 319, 'name' => 'Panchmadai', 'state_id' => 19],
            ['id' => 320, 'name' => 'Panna', 'state_id' => 19],
            ['id' => 321, 'name' => 'Raisen', 'state_id' => 19],
            ['id' => 322, 'name' => 'Rajgarh', 'state_id' => 19],
            ['id' => 323, 'name' => 'Ratlam', 'state_id' => 19],
            ['id' => 324, 'name' => 'Rewa', 'state_id' => 19],
            ['id' => 325, 'name' => 'Sagar', 'state_id' => 19],
            ['id' => 326, 'name' => 'Satna', 'state_id' => 19],
            ['id' => 327, 'name' => 'Sehore', 'state_id' => 19],
            ['id' => 328, 'name' => 'Senapati', 'state_id' => 19],
            ['id' => 329, 'name' => 'Shahdol', 'state_id' => 19],
            ['id' => 330, 'name' => 'Shajapur', 'state_id' => 19],
            ['id' => 331, 'name' => 'Sheopur', 'state_id' => 19],
            ['id' => 332, 'name' => 'Shivpuri', 'state_id' => 19],
            ['id' => 333, 'name' => 'Sidhi', 'state_id' => 19],
            ['id' => 334, 'name' => 'Singrauli', 'state_id' => 19],
            ['id' => 335, 'name' => 'Tikamgarh', 'state_id' => 19],
            ['id' => 336, 'name' => 'Ujjain', 'state_id' => 19],
            ['id' => 337, 'name' => 'Umaria', 'state_id' => 19],
            ['id' => 338, 'name' => 'Vidisha', 'state_id' => 19],
  
            // Maharashtra (MH) - state_id 20
            ['id' => 339, 'name' => 'Ahmednagar', 'state_id' => 20],
            ['id' => 340, 'name' => 'Akola', 'state_id' => 20],
            ['id' => 341, 'name' => 'Amravati', 'state_id' => 20],
            ['id' => 342, 'name' => 'Aurangabad', 'state_id' => 20],
            ['id' => 343, 'name' => 'Bhandara', 'state_id' => 20],
            ['id' => 344, 'name' => 'Buldhana', 'state_id' => 20],
            ['id' => 345, 'name' => 'Chandrapur', 'state_id' => 20],
            ['id' => 346, 'name' => 'Dhule', 'state_id' => 20],
            ['id' => 347, 'name' => 'Gadchiroli', 'state_id' => 20],
            ['id' => 348, 'name' => 'Gondia', 'state_id' => 20],
            ['id' => 349, 'name' => 'Hingoli', 'state_id' => 20],
            ['id' => 350, 'name' => 'Jalna', 'state_id' => 20],
            ['id' => 351, 'name' => 'Jalgaon', 'state_id' => 20],
            ['id' => 352, 'name' => 'Kolhapur', 'state_id' => 20],
            ['id' => 353, 'name' => 'Latur', 'state_id' => 20],
            ['id' => 354, 'name' => 'Mumbai City', 'state_id' => 20],
            ['id' => 355, 'name' => 'Mumbai Suburban', 'state_id' => 20],
            ['id' => 356, 'name' => 'Nagpur', 'state_id' => 20],
            ['id' => 357, 'name' => 'Nanded', 'state_id' => 20],
            ['id' => 358, 'name' => 'Nashik', 'state_id' => 20],
            ['id' => 359, 'name' => 'Osmanabad', 'state_id' => 20],
            ['id' => 360, 'name' => 'Palghar', 'state_id' => 20],
            ['id' => 361, 'name' => 'Parbhani', 'state_id' => 20],
            ['id' => 362, 'name' => 'Ratnagiri', 'state_id' => 20],
            ['id' => 363, 'name' => 'Raigad', 'state_id' => 20],
            ['id' => 364, 'name' => 'Satara', 'state_id' => 20],
            ['id' => 365, 'name' => 'Sindhudurg', 'state_id' => 20],
            ['id' => 366, 'name' => 'Solapur', 'state_id' => 20],
            ['id' => 367, 'name' => 'Thane', 'state_id' => 20],
            ['id' => 368, 'name' => 'Wardha', 'state_id' => 20],
            ['id' => 369, 'name' => 'Washim', 'state_id' => 20],
            ['id' => 370, 'name' => 'Yavatmal', 'state_id' => 20],

            // Manipur (MN) - state_id 21
            ['id' => 371, 'name' => 'Bishnupur', 'state_id' => 21],
            ['id' => 372, 'name' => 'Chandel', 'state_id' => 21],
            ['id' => 373, 'name' => 'Churachandpur', 'state_id' => 21],
            ['id' => 374, 'name' => 'Imphal East', 'state_id' => 21],
            ['id' => 375, 'name' => 'Imphal West', 'state_id' => 21],
            ['id' => 376, 'name' => 'Senapati', 'state_id' => 21],
            ['id' => 377, 'name' => 'Tamenglong', 'state_id' => 21],
            ['id' => 378, 'name' => 'Thoubal', 'state_id' => 21],
            ['id' => 379, 'name' => 'Ukhrul', 'state_id' => 21],

            // Meghalaya (ML) - state_id 22
            ['id' => 380, 'name' => 'East Garo Hills', 'state_id' => 22],
            ['id' => 381, 'name' => 'East Khasi Hills', 'state_id' => 22],
            ['id' => 382, 'name' => 'Jaintia Hills', 'state_id' => 22],
            ['id' => 383, 'name' => 'South Garo Hills', 'state_id' => 22],
            ['id' => 384, 'name' => 'West Garo Hills', 'state_id' => 22],
            ['id' => 385, 'name' => 'West Khasi Hills', 'state_id' => 22],

            // Mizoram (MZ) - state_id 23
            ['id' => 386, 'name' => 'Aizawl', 'state_id' => 23],
            ['id' => 387, 'name' => 'Champhai', 'state_id' => 23],
            ['id' => 388, 'name' => 'Lawngtlai', 'state_id' => 23],
            ['id' => 389, 'name' => 'Lunglei', 'state_id' => 23],
            ['id' => 390, 'name' => 'Mamit', 'state_id' => 23],
            ['id' => 391, 'name' => 'Saiha', 'state_id' => 23],
            ['id' => 392, 'name' => 'Serchhip', 'state_id' => 23],

            // Nagaland (NL) - state_id 24
            ['id' => 393, 'name' => 'Dimapur', 'state_id' => 24],
            ['id' => 394, 'name' => 'Kiphire', 'state_id' => 24],
            ['id' => 395, 'name' => 'Kohima', 'state_id' => 24],
            ['id' => 396, 'name' => 'Longleng', 'state_id' => 24],
            ['id' => 397, 'name' => 'Mokokchung', 'state_id' => 24],
            ['id' => 398, 'name' => 'Mon', 'state_id' => 24],
            ['id' => 399, 'name' => 'Peren', 'state_id' => 24],
            ['id' => 400, 'name' => 'Phek', 'state_id' => 24],
            ['id' => 401, 'name' => 'Tuensang', 'state_id' => 24],
            ['id' => 402, 'name' => 'Wokha', 'state_id' => 24],
            ['id' => 403, 'name' => 'Zunheboto', 'state_id' => 24],

            // Odisha (OR) - state_id 25
            ['id' => 404, 'name' => 'Angul', 'state_id' => 25],
            ['id' => 405, 'name' => 'Balangir', 'state_id' => 25],
            ['id' => 406, 'name' => 'Balasore', 'state_id' => 25],
            ['id' => 407, 'name' => 'Bargarh', 'state_id' => 25],
            ['id' => 408, 'name' => 'Bhadrak', 'state_id' => 25],
            ['id' => 409, 'name' => 'Bolangir', 'state_id' => 25],
            ['id' => 410, 'name' => 'Cuttack', 'state_id' => 25],
            ['id' => 411, 'name' => 'Dhenkanal', 'state_id' => 25],
            ['id' => 412, 'name' => 'Ganjam', 'state_id' => 25],
            ['id' => 413, 'name' => 'Gajapati', 'state_id' => 25],
            ['id' => 414, 'name' => 'Jajpur', 'state_id' => 25],
            ['id' => 415, 'name' => 'Jagatsinghpur', 'state_id' => 25],
            ['id' => 416, 'name' => 'Kalahandi', 'state_id' => 25],
            ['id' => 417, 'name' => 'Kandhamal', 'state_id' => 25],
            ['id' => 418, 'name' => 'Kendrapara', 'state_id' => 25],
            ['id' => 419, 'name' => 'Kendujhar', 'state_id' => 25],
            ['id' => 420, 'name' => 'Khurda', 'state_id' => 25],
            ['id' => 421, 'name' => 'Nabarangpur', 'state_id' => 25],
            ['id' => 422, 'name' => 'Nayagarh', 'state_id' => 25],
            ['id' => 423, 'name' => 'Nuapada', 'state_id' => 25],
            ['id' => 424, 'name' => 'Puri', 'state_id' => 25],
            ['id' => 425, 'name' => 'Rayagada', 'state_id' => 25],
            ['id' => 426, 'name' => 'Sambalpur', 'state_id' => 25],
            ['id' => 427, 'name' => 'Sonepur', 'state_id' => 25],
            ['id' => 428, 'name' => 'Subarnapur', 'state_id' => 25],
            ['id' => 429, 'name' => 'Koraput', 'state_id' => 25],
            ['id' => 430, 'name' => 'Mayurbhanj', 'state_id' => 25],
            ['id' => 431, 'name' => 'Boudh', 'state_id' => 25],

            // Puducherry (PY) - state_id 26
            ['id' => 432, 'name' => 'Karaikal', 'state_id' => 26],
            ['id' => 433, 'name' => 'Mahe', 'state_id' => 26],
            ['id' => 434, 'name' => 'Puducherry', 'state_id' => 26],
            ['id' => 435, 'name' => 'Yanam', 'state_id' => 26],


            // Punjab (PB) - state_id 27
            ['id' => 436, 'name' => 'Amritsar', 'state_id' => 27],
            ['id' => 437, 'name' => 'Barnala', 'state_id' => 27],
            ['id' => 438, 'name' => 'Bathinda', 'state_id' => 27],
            ['id' => 439, 'name' => 'Fatehgarh Sahib', 'state_id' => 27],
            ['id' => 440, 'name' => 'Ferozepur', 'state_id' => 27],
            ['id' => 441, 'name' => 'Gurdaspur', 'state_id' => 27],
            ['id' => 442, 'name' => 'Hoshiarpur', 'state_id' => 27],
            ['id' => 443, 'name' => 'Jalandhar', 'state_id' => 27],
            ['id' => 444, 'name' => 'Kapurthala', 'state_id' => 27],
            ['id' => 445, 'name' => 'Ludhiana', 'state_id' => 27],
            ['id' => 446, 'name' => 'Mansa', 'state_id' => 27],
            ['id' => 447, 'name' => 'Moga', 'state_id' => 27],
            ['id' => 448, 'name' => 'Pathankot', 'state_id' => 27],
            ['id' => 449, 'name' => 'Rupnagar', 'state_id' => 27],
            ['id' => 450, 'name' => 'SAS Nagar', 'state_id' => 27],
            ['id' => 451, 'name' => 'Sangrur', 'state_id' => 27],
            ['id' => 452, 'name' => 'Tarn Taran', 'state_id' => 27],

            // Rajasthan (RJ) - state_id 28
            ['id' => 453, 'name' => 'Ajmer', 'state_id' => 28],
            ['id' => 454, 'name' => 'Alwar', 'state_id' => 28],
            ['id' => 455, 'name' => 'Banswara', 'state_id' => 28],
            ['id' => 456, 'name' => 'Baran', 'state_id' => 28],
            ['id' => 457, 'name' => 'Barmer', 'state_id' => 28],
            ['id' => 458, 'name' => 'Bikaner', 'state_id' => 28],
            ['id' => 459, 'name' => 'Chittorgarh', 'state_id' => 28],
            ['id' => 460, 'name' => 'Churu', 'state_id' => 28],
            ['id' => 461, 'name' => 'Dausa', 'state_id' => 28],
            ['id' => 462, 'name' => 'Dholpur', 'state_id' => 28],
            ['id' => 463, 'name' => 'Dungarpur', 'state_id' => 28],
            ['id' => 464, 'name' => 'Hanumangarh', 'state_id' => 28],
            ['id' => 465, 'name' => 'Jaipur', 'state_id' => 28],
            ['id' => 466, 'name' => 'Jaisalmer', 'state_id' => 28],
            ['id' => 467, 'name' => 'Jalore', 'state_id' => 28],
            ['id' => 468, 'name' => 'Jhalawar', 'state_id' => 28],
            ['id' => 469, 'name' => 'Jhunjhunu', 'state_id' => 28],
            ['id' => 470, 'name' => 'Nagaur', 'state_id' => 28],
            ['id' => 471, 'name' => 'Pali', 'state_id' => 28],
            ['id' => 472, 'name' => 'Rajsamand', 'state_id' => 28],
            ['id' => 473, 'name' => 'Sawai Madhopur', 'state_id' => 28],
            ['id' => 474, 'name' => 'Sikar', 'state_id' => 28],
            ['id' => 475, 'name' => 'Tonk', 'state_id' => 28],
            ['id' => 476, 'name' => 'Udaipur', 'state_id' => 28],

            // Sikkim (SK) - state_id 29
            ['id' => 477, 'name' => 'East Sikkim', 'state_id' => 29],
            ['id' => 478, 'name' => 'North Sikkim', 'state_id' => 29],
            ['id' => 479, 'name' => 'South Sikkim', 'state_id' => 29],
            ['id' => 480, 'name' => 'West Sikkim', 'state_id' => 29],

            // Tamil Nadu (TN) - state_id 30
            ['id' => 481, 'name' => 'Ariyalur', 'state_id' => 30],
            ['id' => 482, 'name' => 'Chennai', 'state_id' => 30],
            ['id' => 483, 'name' => 'Chengalpattu', 'state_id' => 30],
            ['id' => 484, 'name' => 'Coimbatore', 'state_id' => 30],
            ['id' => 485, 'name' => 'Cuddalore', 'state_id' => 30],
            ['id' => 486, 'name' => 'Dharmapuri', 'state_id' => 30],
            ['id' => 487, 'name' => 'Dindigul', 'state_id' => 30],
            ['id' => 488, 'name' => 'Erode', 'state_id' => 30],
            ['id' => 489, 'name' => 'Kallakurichi', 'state_id' => 30],
            ['id' => 490, 'name' => 'Kanchipuram', 'state_id' => 30],
            ['id' => 491, 'name' => 'Kanyakumari', 'state_id' => 30],
            ['id' => 492, 'name' => 'Karur', 'state_id' => 30],
            ['id' => 493, 'name' => 'Madurai', 'state_id' => 30],
            ['id' => 494, 'name' => 'Nagapattinam', 'state_id' => 30],
            ['id' => 495, 'name' => 'Namakkal', 'state_id' => 30],
            ['id' => 496, 'name' => 'Nilgiris', 'state_id' => 30],
            ['id' => 497, 'name' => 'Perambalur', 'state_id' => 30],
            ['id' => 498, 'name' => 'Pudukkottai', 'state_id' => 30],
            ['id' => 499, 'name' => 'Ramanathapuram', 'state_id' => 30],
            ['id' => 500, 'name' => 'Ranipet', 'state_id' => 30],
            ['id' => 501, 'name' => 'Salem', 'state_id' => 30],
            ['id' => 502, 'name' => 'Sivaganga', 'state_id' => 30],
            ['id' => 503, 'name' => 'Thanjavur', 'state_id' => 30],
            ['id' => 504, 'name' => 'Theni', 'state_id' => 30],
            ['id' => 505, 'name' => 'Tiruchirappalli', 'state_id' => 30],
            ['id' => 506, 'name' => 'Tirunelveli', 'state_id' => 30],
            ['id' => 507, 'name' => 'Tiruppur', 'state_id' => 30],
            ['id' => 508, 'name' => 'Vellore', 'state_id' => 30],
            ['id' => 509, 'name' => 'Virudhunagar', 'state_id' => 30],

            // Telangana (TG) - state_id 31
            ['id' => 510, 'name' => 'Adilabad', 'state_id' => 31],
            ['id' => 511, 'name' => 'Karimnagar', 'state_id' => 31],
            ['id' => 512, 'name' => 'Khammam', 'state_id' => 31],
            ['id' => 513, 'name' => 'Mahbubnagar', 'state_id' => 31],
            ['id' => 514, 'name' => 'Medak', 'state_id' => 31],
            ['id' => 515, 'name' => 'Nalgonda', 'state_id' => 31],
            ['id' => 516, 'name' => 'Nizamabad', 'state_id' => 31],
            ['id' => 517, 'name' => 'Rangareddy', 'state_id' => 31],
            ['id' => 518, 'name' => 'Warangal', 'state_id' => 31],
            ['id' => 519, 'name' => 'Hyderabad', 'state_id' => 31],

            // Tripura (TR) - state_id 32
            ['id' => 520, 'name' => 'Dhalai', 'state_id' => 32],
            ['id' => 521, 'name' => 'Gomati', 'state_id' => 32],
            ['id' => 522, 'name' => 'North Tripura', 'state_id' => 32],
            ['id' => 523, 'name' => 'Sepahijala', 'state_id' => 32],
            ['id' => 524, 'name' => 'South Tripura', 'state_id' => 32],
            ['id' => 525, 'name' => 'Unakoti', 'state_id' => 32],
            ['id' => 526, 'name' => 'West Tripura', 'state_id' => 32],

            // Uttar Pradesh (UP) - state_id 33
            ['id' => 527, 'name' => 'Agra', 'state_id' => 33],
            ['id' => 528, 'name' => 'Aligarh', 'state_id' => 33],
            ['id' => 529, 'name' => 'Allahabad', 'state_id' => 33],
            ['id' => 530, 'name' => 'Ambedkar Nagar', 'state_id' => 33],
            ['id' => 531, 'name' => 'Auraiya', 'state_id' => 33],
            ['id' => 532, 'name' => 'Azamgarh', 'state_id' => 33],
            ['id' => 533, 'name' => 'Baghpat', 'state_id' => 33],
            ['id' => 534, 'name' => 'Banda', 'state_id' => 33],
            ['id' => 535, 'name' => 'Barabanki', 'state_id' => 33],
            ['id' => 536, 'name' => 'Bareilly', 'state_id' => 33],
            ['id' => 537, 'name' => 'Basti', 'state_id' => 33],
            ['id' => 538, 'name' => 'Bijnor', 'state_id' => 33],
            ['id' => 539, 'name' => 'Bulandshahr', 'state_id' => 33],
            ['id' => 540, 'name' => 'Chandauli', 'state_id' => 33],
            ['id' => 541, 'name' => 'Chitrakoot', 'state_id' => 33],
            ['id' => 542, 'name' => 'Deoria', 'state_id' => 33],
            ['id' => 543, 'name' => 'Etah', 'state_id' => 33],
            ['id' => 544, 'name' => 'Etawah', 'state_id' => 33],
            ['id' => 545, 'name' => 'Faizabad', 'state_id' => 33],
            ['id' => 546, 'name' => 'Farrukhabad', 'state_id' => 33],
            ['id' => 547, 'name' => 'Fatehpur', 'state_id' => 33],
            ['id' => 548, 'name' => 'Gautam Buddh Nagar', 'state_id' => 33],
            ['id' => 549, 'name' => 'Ghaziabad', 'state_id' => 33],
            ['id' => 550, 'name' => 'Ghazipur', 'state_id' => 33],
            ['id' => 551, 'name' => 'Gonda', 'state_id' => 33],
            ['id' => 552, 'name' => 'Gorakhpur', 'state_id' => 33],
            ['id' => 553, 'name' => 'Hamirpur', 'state_id' => 33],
            ['id' => 554, 'name' => 'Hardoi', 'state_id' => 33],
            ['id' => 555, 'name' => 'Hathras', 'state_id' => 33],
            ['id' => 556, 'name' => 'Jalaun', 'state_id' => 33],
            ['id' => 557, 'name' => 'Jaunpur', 'state_id' => 33],
            ['id' => 558, 'name' => 'Jhansi', 'state_id' => 33],
            ['id' => 559, 'name' => 'Kannauj', 'state_id' => 33],
            ['id' => 560, 'name' => 'Kanpur', 'state_id' => 33],
            ['id' => 561, 'name' => 'Kushinagar', 'state_id' => 33],
            ['id' => 562, 'name' => 'Lakhimpur Kheri', 'state_id' => 33],
            ['id' => 563, 'name' => 'Lalitpur', 'state_id' => 33],
            ['id' => 564, 'name' => 'Lucknow', 'state_id' => 33],
            ['id' => 565, 'name' => 'Maharajganj', 'state_id' => 33],
            ['id' => 566, 'name' => 'Mahoba', 'state_id' => 33],
            ['id' => 567, 'name' => 'Mainpuri', 'state_id' => 33],
            ['id' => 568, 'name' => 'Mathura', 'state_id' => 33],
            ['id' => 569, 'name' => 'Mau', 'state_id' => 33],
            ['id' => 570, 'name' => 'Meerut', 'state_id' => 33],
            ['id' => 571, 'name' => 'Mirzapur', 'state_id' => 33],
            ['id' => 572, 'name' => 'Moradabad', 'state_id' => 33],
            ['id' => 573, 'name' => 'Muzaffarnagar', 'state_id' => 33],
            ['id' => 574, 'name' => 'Pilibhit', 'state_id' => 33],
            ['id' => 575, 'name' => 'Pratapgarh', 'state_id' => 33],
            ['id' => 576, 'name' => 'Raebareli', 'state_id' => 33],
            ['id' => 577, 'name' => 'Rampur', 'state_id' => 33],
            ['id' => 578, 'name' => 'Saharanpur', 'state_id' => 33],
            ['id' => 579, 'name' => 'Sant Ravidas Nagar', 'state_id' => 33],
            ['id' => 580, 'name' => 'Shahjahanpur', 'state_id' => 33],
            ['id' => 581, 'name' => 'Shrawasti', 'state_id' => 33],
            ['id' => 582, 'name' => 'Siddharth Nagar', 'state_id' => 33],
            ['id' => 583, 'name' => 'Sitapur', 'state_id' => 33],
            ['id' => 584, 'name' => 'Sonbhadra', 'state_id' => 33],
            ['id' => 585, 'name' => 'Sultanpur', 'state_id' => 33],
            ['id' => 586, 'name' => 'Unnao', 'state_id' => 33],
            ['id' => 587, 'name' => 'Varanasi', 'state_id' => 33],
            ['id' => 588, 'name' => 'Bijnor', 'state_id' => 33],

            // Uttarakhand (UK) - state_id 34
            ['id' => 589, 'name' => 'Almora', 'state_id' => 34],
            ['id' => 590, 'name' => 'Bageshwar', 'state_id' => 34],
            ['id' => 591, 'name' => 'Chamoli', 'state_id' => 34],
            ['id' => 592, 'name' => 'Champawat', 'state_id' => 34],
            ['id' => 593, 'name' => 'Dehradun', 'state_id' => 34],
            ['id' => 594, 'name' => 'Haridwar', 'state_id' => 34],
            ['id' => 595, 'name' => 'Nainital', 'state_id' => 34],
            ['id' => 596, 'name' => 'Pauri Garhwal', 'state_id' => 34],
            ['id' => 597, 'name' => 'Pithoragarh', 'state_id' => 34],
            ['id' => 598, 'name' => 'Rudraprayag', 'state_id' => 34],
            ['id' => 599, 'name' => 'Tehri Garhwal', 'state_id' => 34],
            ['id' => 600, 'name' => 'Udham Singh Nagar', 'state_id' => 34],
            ['id' => 601, 'name' => 'Uttarkashi', 'state_id' => 34],

            // West Bengal (WB) - state_id 35
            ['id' => 602, 'name' => 'Alipurduar', 'state_id' => 35],
            ['id' => 603, 'name' => 'Bankura', 'state_id' => 35],
            ['id' => 604, 'name' => 'Birbhum', 'state_id' => 35],
            ['id' => 605, 'name' => 'Burdwan', 'state_id' => 35],
            ['id' => 606, 'name' => 'Cooch Behar', 'state_id' => 35],
            ['id' => 607, 'name' => 'Dakshin Dinajpur', 'state_id' => 35],
            ['id' => 608, 'name' => 'Darjeeling', 'state_id' => 35],
            ['id' => 609, 'name' => 'Hooghly', 'state_id' => 35],
            ['id' => 610, 'name' => 'Howrah', 'state_id' => 35],
            ['id' => 611, 'name' => 'Jalpaiguri', 'state_id' => 35],
            ['id' => 612, 'name' => 'Jhargram', 'state_id' => 35],
            ['id' => 613, 'name' => 'Kalimpong', 'state_id' => 35],
            ['id' => 614, 'name' => 'Koch Bihar', 'state_id' => 35],
            ['id' => 615, 'name' => 'Malda', 'state_id' => 35],
            ['id' => 616, 'name' => 'Murshidabad', 'state_id' => 35],
            ['id' => 617, 'name' => 'Nadia', 'state_id' => 35],
            ['id' => 618, 'name' => 'North 24 Parganas', 'state_id' => 35],
            ['id' => 619, 'name' => 'Paschim Bardhaman', 'state_id' => 35],
            ['id' => 620, 'name' => 'Paschim Medinipur', 'state_id' => 35],
            ['id' => 621, 'name' => 'Purba Bardham','state_id' => 35]

        ];

        foreach ($cities as $city) {
            DB::table('cities')->insert([
                'id' => $city['id'],
                'name' => $city['name'],
                'state_id' => $city['state_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
